# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CPPlwls1d_LR <- function(bw, kernel_type, win, xin, yin, xout, npoly = 1L, nder = 0L) {
    .Call(`_FPMD_CPPlwls1d_LR`, bw, kernel_type, win, xin, yin, xout, npoly, nder)
}

RCPPmean <- function(X) {
    .Call(`_FPMD_RCPPmean`, X)
}

RCPPvar <- function(X) {
    .Call(`_FPMD_RCPPvar`, X)
}

Rrotatedmullwlsk <- function(bw, kernel_type, tPairs, cxxn, win, xygrid, npoly, bwCheck) {
    .Call(`_FPMD_Rrotatedmullwlsk`, bw, kernel_type, tPairs, cxxn, win, xygrid, npoly, bwCheck)
}

interp2lin <- function(xin, yin, zin, xou, you) {
    .Call(`_FPMD_interp2lin`, xin, yin, zin, xou, you)
}

